apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-console-ng
  namespace: default
  labels:
    app: rocketmq-console-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-console-ng
  template:
    metadata:
      labels:
        name: rocketmq-console-ng
        app: rocketmq-console-ng
    spec:
      containers:
      - name: rocketmq-console-ng
        image: styletang/rocketmq-console-ng
        #image: slpcat/rocketmq-console-ng
        ports:
          - name: web
            containerPort: 8080
        env:
          - name: JAVA_OPTS
            value: "-Drocketmq.namesrv.addr=rocketmq-svc:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false -server -Djava.awt.headless=true -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=240M -XX:MaxRAMFraction=1 -XshowSettings:vm -XX:+AggressiveOpts -XX:+UseBiasedLocking -XX:+UseFastAccessorMethods -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:G1ReservePercent=25 -XX:G1NewSizePercent=10 -XX:G1MaxNewSizePercent=25 -XX:MaxGCPauseMillis=20 -XX:-OmitStackTraceInFastThrow -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=8 -XX:MaxTenuringThreshold=15 -XX:G1HeapWastePercent=10 -XX:SurvivorRatio=8 -XX:G1MixedGCCountTarget=16 -XX:G1MixedGCLiveThresholdPercent=90 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=32m -XX:-ResizePLAB"
      #volumeMounts:
      #- name: config-volume
      #  mountPath: /opt/rocketmq-console/bin
      #volumes:
      #  - name: config-volume
      #    configMap:
      #      name: runbroker.sh
