---
kind: Service
apiVersion: v1
metadata:
  labels:
      app: rocketmq
  name: rocketmq-svc
spec:
  ports:
  - port: 9876
    targetPort: 9876
    name: namesrv
  - port: 10911
    targetPort: 10911
    name: broker
  clusterIP: None
  selector:
    app: rocketmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: rocketmq
  name: rocketmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq
  serviceName: rocketmq-svc
  template:
    metadata:
      labels:
        app: rocketmq
        name: rocketmq
      annotations:
        #disable istio sidecar injection
        sidecar.istio.io/inject: "false"
        #net.ipv4.tcp_syncookies=0 need kernel version 4.4 or newer
        security.alpha.kubernetes.io/sysctls: "net.ipv4.tcp_syncookies=0,net.ipv4.ip_local_port_range=10000 65535"
        #kernel version 4.15 needed
        security.alpha.kubernetes.io/unsafe-sysctls: "net.core.somaxconn=65535,net.ipv4.tcp_tw_reuse=1,net.ipv4.tcp_fin_timeout=30,net.ipv4.tcp_keepalive_intvl=4,net.ipv4.tcp_keepalive_probes=3,net.ipv4.tcp_keepalive_time=120,net.ipv4.tcp_max_syn_backlog=65535,net.ipv4.tcp_rfc1337=1,net.ipv4.tcp_slow_start_after_idle=0,net.ipv4.tcp_fack=1,net.ipv4.tcp_fwmark_accept=1,net.ipv4.fwmark_reflect=1"
    spec:
      containers:
      - image: slpcat/rocketmq
        imagePullPolicy: Always
        name: rocketmq
        ports:
        - containerPort: 9876
          name: namesrv
          protocol: TCP
        - containerPort: 10909
          name: vip
          protocol: TCP
        - containerPort: 10911
          name: broker
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - mountPath: /opt/rocketmq/store
          name: rocketmq-store
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1000:1000 /opt/rocketmq/store
        image: busybox
        imagePullPolicy: Always
        name: volume-mount-uid
        volumeMounts:
        - mountPath: /opt/rocketmq/store
          name: rocketmq-store
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: rocketmq-store
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
