kind: Service
apiVersion: v1
metadata:
  name: rocketmqcluster-broker-master
  labels:
      app: rocketmqcluster-broker-master
spec:
  ports:
  - port: 9876
    targetPort: 9876
    name: namesrv
  - port: 10911
    targetPort: 10911
    name: broker
  clusterIP: None
  selector:
    app: rocketmqcluster-broker-master
