apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmqcluster-broker-slave
  labels:
    app: rocketmqcluster-broker-slave
spec:
  serviceName: rocketmqcluster-broker-slave
  replicas: 3
  selector:
    matchLabels:
      app: rocketmqcluster-broker-slave
  template:
    metadata:
      labels:
        name: rocketmqcluster-broker-slave
        app: rocketmqcluster-broker-slave
      annotations:
        #disable istio sidecar injection
        #sidecar.istio.io/inject: "false"
        #scheduler.alpha.kubernetes.io/critical-pod=""
        #net.ipv4.tcp_syncookies=0 need kernel version 4.4 or newer
        security.alpha.kubernetes.io/sysctls: "net.ipv4.tcp_syncookies=0,net.ipv4.ip_local_port_range=10000 65535"
        #kernel version >= 4.15 needed
        security.alpha.kubernetes.io/unsafe-sysctls: "net.core.somaxconn=65535,net.ipv4.ip_unprivileged_port_start=0,net.ipv4.tcp_tw_reuse=1,net.ipv4.tcp_fin_timeout=30,net.ipv4.tcp_keepalive_intvl=10,net.ipv4.tcp_keepalive_probes=2,net.ipv4.tcp_keepalive_time=120,net.ipv4.tcp_ecn=1,net.ipv4.tcp_max_syn_backlog=65535,net.ipv4.tcp_rfc1337=1,net.ipv4.tcp_slow_start_after_idle=0,net.ipv4.tcp_fack=1,net.ipv4.tcp_max_tw_buckets=262144,net.ipv4.tcp_fastopen=3,net.ipv4.icmp_ratelimit=100,net.ipv4.tcp_abort_on_overflow=1,net.ipv4.tcp_adv_win_scale=2,net.ipv4.tcp_retries2=8,net.ipv4.tcp_syn_retries=3,net.ipv4.tcp_synack_retries=2,net.unix.max_dgram_qlen=512,net.ipv4.tcp_fwmark_accept=1,net.ipv4.fwmark_reflect=1,net.ipv4.tcp_no_metrics_save=1,net.ipv4.vs.conn_reuse_mode=0,net.ipv4.vs.conntrack=1,net.netfilter.nf_conntrack_helper=1,net.netfilter.nf_conntrack_max=1048576,net.netfilter.nf_conntrack_tcp_timeout_close_wait=60,net.netfilter.nf_conntrack_tcp_timeout_established=120,net.netfilter.nf_conntrack_tcp_timeout_fin_wait=30,net.netfilter.nf_conntrack_tcp_timeout_last_ack=30,net.netfilter.nf_conntrack_tcp_timeout_time_wait=60"
    spec:
      initContainers:
        - name: volume-mount-uid
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /opt/rocketmq/store"]
          volumeMounts:
          - name: rocketmq-store
            mountPath: /opt/rocketmq/store
      containers:
      - name: rocketmq
        image: slpcat/rocketmq
        command:
        - sh
        - -c
        - ./rkGenConfig.sh && ./mqbroker -c ../conf/broker.conf -n $ROCKETMQ_NAMESERVER 2>&1
        env:
        - name : ROCKETMQ_NAMESERVER
          value: "rocketmqcluster-nameserver-0.rocketmqcluster-nameserver:9876;rocketmqcluster-nameserver-1.rocketmqcluster-nameserver:9876"
        resources:
          # keep request = limit to keep this container in guaranteed class
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 4
            memory: 8Gi
        ports:
          - name: namesrv
            containerPort: 9876
          - name: vip
            containerPort: 10909
          - name: broker
            containerPort: 10911
        volumeMounts:
          - name: rocketmq-store
            mountPath: /opt/rocketmq/store
          - name: brocker-conf
            mountPath: "/opt/rocketmq/conf/broker.conf.sample"
            subPath: broker.conf.sample
      volumes:
        - name: brocker-conf
          configMap:
            name: rocketmqcluster-configmap
            #Add ConfigMap data to a specific path in the Volume
            items:
            - key: broker.conf.sample
              path: broker.conf.sample
  volumeClaimTemplates:
  - metadata:
      name: rocketmq-store
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
