apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-master
  namespace: default
  labels:
    app: hbase-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hbase-master
#  minReadySeconds: 60     #滚动升级时60s后认为该pod就绪
  serviceName: hbase-master
  template:
    metadata:
      labels:
        app: hbase-master
      annotations:
        #disable istio sidecar injection
        sidecar.istio.io/inject: "false"
        #net.ipv4.tcp_syncookies=0 need kernel version 4.4 or newer
        security.alpha.kubernetes.io/sysctls: "net.ipv4.tcp_syncookies=0,net.ipv4.ip_local_port_range=10000 65535"
        #kernel version 4.15 needed
        security.alpha.kubernetes.io/unsafe-sysctls: "net.core.somaxconn=65535,net.ipv4.tcp_tw_reuse=1,net.ipv4.tcp_fin_timeout=30,net.ipv4.tcp_keepalive_intvl=4,net.ipv4.tcp_keepalive_probes=3,net.ipv4.tcp_keepalive_time=120,net.ipv4.tcp_max_syn_backlog=65535,net.ipv4.tcp_rfc1337=1,net.ipv4.tcp_slow_start_after_idle=0,net.ipv4.tcp_fack=1,net.ipv4.tcp_max_tw_buckets=262144,net.ipv4.tcp_fastopen=3,net.ipv4.icmp_ratelimit=100,net.ipv4.tcp_abort_on_overflow=1,net.ipv4.tcp_adv_win_scale=2,net.ipv4.tcp_retries2=8,net.ipv4.tcp_syn_retries=3,net.ipv4.tcp_synack_retries=2,net.unix.max_dgram_qlen=512,net.ipv4.tcp_fwmark_accept=1,net.ipv4.fwmark_reflect=1,net.ipv4.tcp_no_metrics_save=1,net.netfilter.nf_conntrack_helper=1,net.netfilter.nf_conntrack_max=1048576,net.netfilter.nf_conntrack_tcp_timeout_close_wait=60,net.netfilter.nf_conntrack_tcp_timeout_established=120,net.netfilter.nf_conntrack_tcp_timeout_fin_wait=30,net.netfilter.nf_conntrack_tcp_timeout_last_ack=30,net.netfilter.nf_conntrack_tcp_timeout_time_wait=60"
    spec:
      #nodeName: k8s.node1 #指定调度节点为k8s.node1
      #nodeSelector:  #调度特定的节点
      #  env: test-team
      terminationGracePeriodSeconds: 60 ##k8s将会给应用发送SIGTERM信号，可以用来正确、优雅地关闭应用,默认为30秒
      #imagePullSecrets:
      #- name: registrykey-ali-ext
      containers:
      - name: hbase-master
        #image: slpcat/hbase:centos7
        image: slpcat/hbase:alpine
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 4
            #nvidia.com/gpu: 1
            memory: 8Gi
        securityContext:
          capabilities: {}
          privileged: false
        env:
        - name: HBASE_SERVER_TYPE
          value: master
        - name: HDFS_PATH
          #hdfs headless service
          value: hadoop-hadoop-hdfs-nn:9000
        - name: ZOOKEEPER_SERVICE_LIST
          #zookeeper headless service
          value: zookeeper-1,zookeeper-2,zookeeper-3
        - name: ZOOKEEPER_PORT
          value: "2181"
        - name: ZNODE_PARENT
          value: hbase
        ports:
        - containerPort: 16000
          protocol: TCP
        - containerPort: 16010
          name: hmaster-ui
          protocol: TCP
