apiVersion: v1
data:
  dubbo.properties: |-
    dubbo.application.name=dubbo-monitor-ui
    dubbo.application.owner=xkx
    dubbo.registry.protocol=zookeeper
    dubbo.registry.address=zk-cs:2181
     #slave-01:2181,slave-02:2181,slave-03:2181
    #use netty4
    #dubbo.reference.client=netty4

    #peeper config
    peeper.zookeepers=zk-cs:2181
      #
    peeper.zookeeper.session.timeout=60000

    #logger
    monitor.log.home=/workspace/logs

    monitor.collect.interval=6000

    auth.key=g2eeOzk=lavj1Hqx
kind: ConfigMap
metadata:
  name: dubbokeeper
  namespace: default
