apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dubbokeeper
  name: dubbokeeper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbokeeper
  template:
    metadata:
      labels:
        app: dubbokeeper
    spec:
      containers:
        image: slpcat/dubbokeeper:v1.0.1
        imagePullPolicy: Always
        name: dubbokeeper
        ports:
        - containerPort: 8080
          name: tomcat
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 50m
            memory: 1Gi
        volumeMounts:
        - mountPath: /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/dubbo.properties
          name: configmap
          subPath: dubbo.properties
      dnsPolicy: ClusterFirst
      #imagePullSecrets:
      #- name: registrykey-ali-vpc
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          defaultMode: 420
          name: dubbomonitor
        name: configmap
