apiVersion: v1
kind: Service
metadata:
  name: pinpoint-collector-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: pinpoint-collector
  ports:
    - name: base
      port: 9994
      protocol: TCP
    - name: p1
      port: 9995
      protocol: TCP
    - name: p2
      port: 9996
      protocol: TCP
    - name:p3
      port: 9995
      protocol: UDP
    - name: p4
      port: 9996
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: pinpoint-collector
spec:
  selector:
    app: pinpoint-collector
  ports:
    - name: http
      port: 8080
  type: NodePort
